[package]
name = "imshow"
version = "0.2.0"
authors = ["Michaël Lévesque-Dion <mlevesquedion@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.23.4"
clap = "2.33.0"
term_size = "0.3.2"
ansi_term = "0.12.1"
rayon = "1.3.0"
itertools = "0.9.0"
